// import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  UserButton,
  SignedOut,
} from '@clerk/nextjs'
import { Button } from "@/components/ui/button";
import { icons, Plus, Sparkle } from "lucide-react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: "Imagine",
  description: "Generate stunning AI-powered images instantly. Create unique artwork, illustrations, and visuals with our easy-to-use image generation web app.",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          className="h-screen flex flex-col m-0"
        >
          <header className="flex flex-wrap md:flex-nowrap justify-between items-center p-5 h-auto">
            <div className="w-1/2 md:w-auto bg-clip-text bg-gradient-to-r from-pink-500 via-purple-500 to-indigo-500 pb-2 select-none">
              <SignedOut>
              <Link href="/" className="flex items-center gap-2">
                <Sparkle className="h-8 w-8 text-purple-600" />
                <h1 className="text-2xl font-bold text-transparent">
                  imagine
                </h1>
              </Link>
              </SignedOut>
              <SignedIn>
              <Link href="/dashboard" className="flex items-center gap-2">
                <Sparkle className="h-8 w-8 text-purple-600" />
                <h1 className="text-2xl font-bold text-transparent">
                  imagine
                </h1>
              </Link>
              </SignedIn>
            </div>
            <div className="w-full order-3 md:order-none md:w-auto mt-2 md:mt-0 flex gap-2 items-center overflow-scroll scrollbar-hidden">
              <SignedIn>
                <Link className="flex-1" href={"/dashboard"}>
                  <Button className="w-full font-bold" variant="secondary">Dashboard</Button>
                </Link>
                <Link className="flex-1" href={"/explore"}>
                  <Button className="font-bold w-full" variant="secondary">
                    Explore
                  </Button>
                </Link>
                <Link className="flex-1" href="/generate">
                  <Button className="md:hidden font-bold w-full bg-purple-600 hover:bg-purple-700">
                    <Plus className="h-4 w-4 mr-1" />
                    Create
                  </Button>
                </Link>
              </SignedIn>
            </div>
            <nav className="w-1/2 md:w-auto flex gap-5 items-center justify-end-safe">
              <SignedIn>
                <Link href={"/generate"}>
                  <Button size="sm" className=" hidden md:flex font-bold bg-purple-600 hover:bg-purple-700">
                    <Plus className="h-4 w-4 mr-1" />
                    Create
                  </Button>
                </Link>
                <UserButton />
              </SignedIn>
              <SignedOut>
                <Link href={"/sign-in"}>
                  <Button size="sm">
                    Sign In
                  </Button>
                </Link>
              </SignedOut>
            </nav>
          </header>
          <main className="p-5 pt-0 flex-1 overflow-auto scrollbar-hidden border-0 flex justify-center">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}